//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumProjectTracking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScrumEntities : DbContext
    {
        public ScrumEntities()
            : base("name=ScrumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Sprints> Tbl_Sprints { get; set; }
        public virtual DbSet<Tbl_Teams> Tbl_Teams { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
    }
}
