//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumProjectTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sprints
    {
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string SprintName { get; set; }
    }
}
