//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumProjectTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Teams
    {
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamType { get; set; }
        public Nullable<bool> Active { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
