//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumProjectTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sprints_Tasks
    {
        public int TaskID { get; set; }
        public int ProjectID { get; set; }
        public int TeamID { get; set; }
        public string SprintName { get; set; }
        public string AssignedUserID { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public Nullable<int> StoryPoints { get; set; }
    }
}
